#!/usr/bin/env python3
# =============================================================================
# Wave-M2 — mapping-corpus case manifest generator (GM1/GM2)
# =============================================================================
# Reads oas31-jsts/mprofile/m-corpus.yaml and emits the C++ include the M
# driver consumes (phase2_m.inc): every row = (id, schema, payload,
# expected class).  Self-checks at generation time:
#   * every expected class is one of the five taxonomy classes;
#   * every referenced schema is in the generated model set;
#   * every instance text parses as JSON (transport rows parse-fail BY
#     DESIGN and are exempt: they still get a python-side parse check that
#     must FAIL);
#   * no duplicate case ids.
# A self-check failure aborts generation (never a silent empty manifest).
# =============================================================================

import os
import sys
import json

import yaml

COMPLIANCE_DIR = os.environ.get(
    "SCRIPT_DIR", os.path.abspath(os.path.dirname(__file__)))
CORPUS = os.environ.get(
    "M_CORPUS",
    os.path.join(os.path.dirname(COMPLIANCE_DIR), "oas31-jsts", "mprofile",
                 "m-corpus.yaml"))
OUT_INC = os.environ.get("PHASE2_M_INC",
                         os.path.join(COMPLIANCE_DIR, "phase2_m.inc"))

CLASSES = ("transportParseError", "schemaInvalid", "unrepresentable",
           "representable", "narrowed")

# The generated model axis the driver compiles against.
SCHEMAS = {
    "Int32Box", "Int64Box", "FloatBox", "DoubleBox", "StringBox", "BoolBox",
    "EnumBox", "NullableBox", "AnyType", "PolyBox", "CollectionBox",
}


def c_quote(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    errors = []
    with open(CORPUS) as f:
        spec = yaml.safe_load(f) or {}
    cases = spec.get("cases", []) if isinstance(spec, dict) else spec

    seen = set()
    emitted = []
    for row in cases:
        rid = row.get("id")
        schema = row.get("schema")
        payload = row.get("instance")
        expected = row.get("expected")
        if not rid:
            errors.append("row without id")
            continue
        if rid in seen:
            errors.append(f"duplicate id {rid}")
        seen.add(rid)
        if expected not in CLASSES:
            errors.append(f"{rid}: unknown expected class {expected!r}")
        if schema not in SCHEMAS:
            errors.append(f"{rid}: schema {schema!r} not in the generated set")
        # instance text: transport rows must FAIL to parse; all others must
        # parse (the corpus rows are literal JSON instances).
        try:
            json.loads(payload)
            if expected == "transportParseError":
                errors.append(f"{rid}: transportParseError row parse must FAIL")
        except Exception:
            if expected != "transportParseError":
                errors.append(f"{rid}: instance does not parse")
        emitted.append((rid, schema, payload, expected))

    if errors:
        for e in errors:
            print("M-CORPUS ERROR:", e, file=sys.stderr)
        print(f"__M_GEN_ERRORS__={len(errors)}", file=sys.stderr)
        return 1

    os.makedirs(os.path.dirname(OUT_INC) or ".", exist_ok=True)
    with open(OUT_INC, "w") as f:
        f.write("// AUTO-GENERATED by phase2_m_gen.py — do not edit.\n")
        f.write("// M-corpus rows for the Wave-M2 driver.\n\n")
        f.write("struct MCase {\n")
        f.write("    const char* id;\n")
        f.write("    const char* schema;\n")
        f.write("    const char* payload;\n")
        f.write("    const char* expected;  // one of the five classes\n")
        f.write("};\n\n")
        f.write("static const MCase kMCases[] = {\n")
        for rid, schema, payload, expected in emitted:
            f.write(f'    {{"{c_quote(rid)}", "{schema}", '
                    f'"{c_quote(payload)}", "{expected}"}},\n')
        f.write("};\n\n")
        f.write(f"static const std::size_t kMCaseCount = {len(emitted)};\n")

    classes = {}
    for rid, schema, payload, expected in emitted:
        classes[expected] = classes.get(expected, 0) + 1
    print(f"__M_GEN_TOTAL__={len(emitted)}")
    for cls in CLASSES:
        print(f"__M_GEN_{cls.upper()}__={classes.get(cls, 0)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())